export const UPDATE_HEADER_SIZE = 'UPDATE_HEADER_SIZE';
export const UPDATE_BODY_HEIGHT = 'UPDATE_BODY_HEIGHT';
export const UPDATE_MARGIN = 'UPDATE_MARGIN';
export const UPDATE_DEVICE_WIDTH_CLASS = 'UPDATE_DEVICE_WIDTH_CLASS';
export const UPDATE_FONT_FACTOR = 'UPDATE_FONT_FACTOR';
export const UPDATE_UID = 'UPDATE_UID';
export const LOADING_POSTS_INITIATED = 'LOADING_POSTS_INITIATED';
export const LOADING_POSTS_FIRST_BATCH_SUCCESSFUL =
    'LOADING_POSTS_FIRST_BATCH_SUCCESSFUL';
export const LOADING_POSTS_SUCCESSFUL = 'LOADING_POSTS_SUCCESSFUL';
export const LOADING_POSTS_FAILED = 'LOADING_POSTS_FAILED';
export const REFRESHING_POSTS_INITIATED = 'REFRESHING_POSTS_INITIATED';
export const REFRESHING_POSTS_SUCCESSFUL = 'REFRESHING_POSTS_SUCCESSFUL';
export const REFRESHING_POSTS_FAILED = 'REFRESHING_POSTS_FAILED';
export const SEARCH_POSTS_INITIATED = 'SEARCH_POSTS_INITIATED';
export const SEARCH_POSTS_SUCCESSFUL = 'SEARCH_POSTS_SUCCESSFUL';
export const SEARCH_POSTS_FIRST_BATCH_SUCCESSFUL =
    'SEARCH_POSTS_FIRST_BATCH_SUCCESSFUL';
export const SEARCH_POSTS_FAILED = 'SEARCH_POSTS_FAILED';
export const SEARCH_ACTIVE = 'SEARCH_ACTIVE';
export const SEARCH_NOT_ACTIVE = 'SEARCH_NOT_ACTIVE';
export const SHOW_FOOTER = 'SHOW_FOOTER';
export const UPDATE_EFFECTIVE_BODY_HEIGHT = 'UPDATE_EFFECTIVE_BODY_HEIGHT';
